-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 01-06-2023 a las 20:12:24
-- Versión del servidor: 10.4.22-MariaDB
-- Versión de PHP: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `proyectoentrenamiento`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `entrenamiento`
--

CREATE TABLE `entrenamiento` (
  `nombre` varchar(80) DEFAULT NULL,
  `nivel` int(11) DEFAULT NULL,
  `lugar` int(11) DEFAULT NULL,
  `tipoEntreno` int(11) DEFAULT NULL,
  `email_usuario` varchar(80) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `entrenamiento`
--

INSERT INTO `entrenamiento` (`nombre`, `nivel`, `lugar`, `tipoEntreno`, `email_usuario`) VALUES
('Lunes', 1, 1, 1, 'carlos'),
('Lunes', 0, 1, 1, 'chicu'),
('Lunes', 1, 1, 1, 'polo'),
('Lunes', 1, 1, 1, 'dd'),
('lunes', 1, 1, 1, 'ju'),
('lunes', 2, 1, 0, 'e'),
('lunes', 1, 0, 0, 'aaa'),
('lunes', 2, 0, 0, 'a'),
('lunes', 2, 0, 2, 'b'),
('lunes', 1, 0, 0, 'bbb'),
('lunes', 1, 0, 2, 'as'),
('lunes', 2, 1, 1, 'v'),
('lunes', 1, 1, 2, 'josse');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `listaejercicio`
--

CREATE TABLE `listaejercicio` (
  `titulo` varchar(20) DEFAULT NULL,
  `nombre` varchar(80) DEFAULT NULL,
  `descripcion` varchar(80) DEFAULT NULL,
  `imagen` varchar(50) DEFAULT NULL,
  `explicacion` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `listaejercicio`
--

INSERT INTO `listaejercicio` (`titulo`, `nombre`, `descripcion`, `imagen`, `explicacion`) VALUES
('Pecho', 'Press Banca', 'Levantar barra con el pecho', 'PressBanca.jpg', '1.	Colocar los pies firmemente en el suelo y acostarse en el banco con los ojos debajo de la barra.\n2.	Agarrar la barra con las manos un poco más anchas que los hombros, los dedos hacia arriba y los pulgares envueltos alrededor de la barra.\n3.	Levantar la barra del soporte y llevarla a la posición sobre el pecho, manteniendo los codos doblados.\n4.	Bajar lentamente la barra hasta que toque ligeramente el pecho, manteniendo los codos cerca del cuerpo y controlando el movimiento.\n5.	Empujar la barra hacia arriba, extendiendo los brazos hasta que estén completamente rectos.\n6.	Volver a bajar la barra lentamente hasta que toque el pecho de nuevo y repetir el movimiento.'),
('Pecho', 'Lagartija', 'Desde el suelo empujar con las manos', 'Lagartija.jpg', '1.	Comienza colocándote boca abajo en el suelo, con las manos a la altura de los hombros y los dedos apuntando hacia adelante. Los brazos deben estar completamente extendidos.\n2.	Levanta tu cuerpo apoyándote en las palmas de las manos y los dedos de los pies. Mantén las piernas rectas y los músculos abdominales contraídos. Esta es la posición inicial.\n3.	Baja lentamente tu cuerpo flexionando los brazos, manteniendo el cuerpo recto. Asegúrate de mantener los codos cerca de los costados y no dejarlos abrirse hacia afuera.\n4.	Continúa bajando hasta que tu pecho esté cerca del suelo o hasta donde te sientas cómodo. Mantén la cabeza recta y la mirada hacia el frente.\n5.	Luego, empuja con fuerza el suelo con las palmas de las manos para volver a la posición inicial, extendiendo completamente los brazos.\n6.	Repite el movimiento de forma controlada y continua, manteniendo la buena forma durante todo el ejercicio.\n'),
('Pecho', 'Press Superior Banca', 'Levantar barra con el pecho en banco inclinado en 45º', 'press_inclinado_barra.png', '1. Comienza de pie con los pies separados a la altura de los hombros. Coloca la barra en el soporte de la máquina o en el suelo, a una altura que te permita levantarla cómodamente sobre tus hombros.\n2. Acércate a la barra y coloca tus manos a una distancia ligeramente más ancha que el ancho de tus hombros. Agarra la barra con un agarre pronunciado (palmas hacia afuera) y asegúrate de que tus pulgares estén envueltos alrededor de la barra.\n3. Con la espalda recta, los hombros hacia atrás y el pecho levantado, levanta la barra sobre tus hombros hasta que esté en posición de partida. Asegúrate de que tus codos estén apuntando hacia adelante y tus antebrazos estén perpendiculares al suelo.\n4. Desde la posición de partida, exhala y empuja la barra hacia arriba hasta que tus brazos estén completamente extendidos. Mantén la barra sobre tu cabeza durante un segundo y luego comienza a bajarla lentamente hacia la posición de partida.\n5. A medida que bajas la barra, inhala y dobla ligeramente las rodillas y las caderas para absorber el impacto. Evita que la barra toque tu pecho o tu cuello durante el descenso, manteniéndola controlada en todo momento.\n6. Una vez que la barra esté de nuevo en la posición de partida, repite el movimiento para completar el número deseado de repeticiones.'),
('Pecho', 'Fondos paralelas', 'Tumbado en el suelo, elevar la cadera hacia arriba y traer los brazos hacia los ', 'Fondos_paralelas.jpg', '1 Comienza colocándote entre dos barras paralelas fijas, como las que se encuentran en las estaciones de fondos de un gimnasio. Sujétate de las barras con las palmas de las manos hacia abajo y los brazos completamente extendidos. Mantén una separación de aproximadamente el ancho de los hombros entre las barras.\n2 Levanta los pies del suelo y cruza las piernas o mantenlas estiradas frente a ti, según tu preferencia.\n3 Manteniendo los brazos rectos, exhala y dobla los codos para comenzar a bajar el cuerpo hacia abajo. Mantén el torso erguido y los hombros hacia atrás mientras desciendes.\n4 Continúa bajando hasta que los hombros estén a la altura de los codos o ligeramente por debajo de ellos. Mantén los codos cerca del cuerpo y evita que se desplacen hacia afuera.\n5 Desde la posición más baja, inhala y comienza a empujar hacia arriba, extendiendo los brazos y volviendo a la posición inicial.\n6 Repite el movimiento para completar el número deseado de repeticiones.'),
('Hombros', 'Elevaciones laterales mancuernas', 'Levantar macuernas lateralmente hasta altura del hombro', 'Elevaciones_laterales_hombros.png', '1.	Toma una mancuerna en cada mano y colócate de pie con los pies separados a la anchura de los hombros. Mantén las rodillas ligeramente flexionadas.\n2.	Mantén una postura erguida con la espalda recta y los hombros hacia abajo y hacia atrás. Este será tu punto de partida.\n3.	Con las mancuernas en las manos, levanta los brazos hacia los lados hasta que estén paralelos al suelo. Los codos deben estar ligeramente flexionados, pero no completamente rectos.\n4.	A medida que levantes los brazos, mantén la atención en los músculos deltoides laterales. Concéntrate en sentir la contracción en esa zona mientras levantas los brazos.\n5.	Haz una breve pausa en la posición más alta, cuando los brazos estén paralelos al suelo. Mantén la contracción en los deltoides laterales.\n6.	Luego, de manera controlada, baja los brazos lentamente hacia el punto de partida, evitando movimientos bruscos o balanceos.\n7.	Repite el movimiento para el número deseado de repeticiones.\n'),
('Hombros', 'Press Militar con barra', 'Levantar barra desde cuello hasta encima de la cabeza en banco plano 90º', 'Press_militar_barra.png', '1 Comienza colocándote entre dos barras paralelas fijas, como las que se encuentran en las estaciones de fondos de un gimnasio. Sujétate de las barras con las palmas de las manos hacia abajo y los brazos completamente extendidos. Mantén una separación de aproximadamente el ancho de los hombros entre las barras.\n2 Levanta los pies del suelo y cruza las piernas o mantenlas estiradas frente a ti, según tu preferencia.\n3 Manteniendo los brazos rectos, exhala y dobla los codos para comenzar a bajar el cuerpo hacia abajo. Mantén el torso erguido y los hombros hacia atrás mientras desciendes.\n4 Continúa bajando hasta que los hombros estén a la altura de los codos o ligeramente por debajo de ellos. Mantén los codos cerca del cuerpo y evita que se desplacen hacia afuera.\n5 Desde la posición más baja, inhala y comienza a empujar hacia arriba, extendiendo los brazos y volviendo a la posición inicial.\n6 Repite el movimiento para completar el número deseado de repeticiones.'),
('Hombros', 'Flexiones pirámide', 'Tumbado en el suelo, elevar la cadera hacia arriba y traer los brazos hacia los ', 'Flexiones_para_hombros.png', '1.Comienza colocándote en posición de plancha alta, con las manos apoyadas en el suelo a la altura de los hombros y los brazos extendidos. Tus manos deben estar ligeramente más anchas que el ancho de los hombros.\n2.	Asegúrate de que tus pies estén juntos y tus piernas extendidas, creando una línea recta desde la cabeza hasta los talones. Este será tu punto de partida.\n3.	Mantén los codos ligeramente flexionados y las palmas de las manos firmemente apoyadas en el suelo.\n4.	Desde esta posición, comienza a bajar el torso hacia el suelo, manteniendo los codos ligeramente doblados.\n5.	A medida que desciendes, enfoca la contracción en los músculos del hombro y mantén la tensión en esa área.\n6.	Baja hasta donde puedas controlar el movimiento sin forzar las articulaciones del hombro o sentir dolor.\n7.	Luego, empuja hacia arriba a través de las palmas de las manos, extendiendo los codos y volviendo a la posición inicial.\n8.	Repite el movimiento para el número deseado de repeticiones.'),
('Hombros', 'Elevaciones frontales con bandas elástica', 'Agarra un extremo de la banda y pisa el otro extremo. Desde el brazo hacia abajo', 'Elevaciones_frontales_banda.png', '\n1 Comienza de pie con los pies separados a la anchura de los hombros y coloca la banda elástica debajo de los pies. Asegúrate de que la banda esté tensa pero no demasiado estirada.\n2 Agarra las asas de la banda con las palmas de las manos hacia abajo y los brazos estirados a lo largo de tu cuerpo. Mantén una ligera flexión en los codos.\n3 Contrae el núcleo y mantén una postura erguida. Este será tu punto de partida.\n4 Exhala y levanta los brazos hacia adelante frente a ti, manteniendo los brazos rectos. Levanta los brazos a la altura de los hombros o ligeramente por encima de ellos. Los brazos deben estar paralelos al suelo.\n5 Mantén una breve pausa en la posición superior, sintiendo la contracción en el deltoides anterior.\n6 Inhala y lentamente baja los brazos de vuelta a la posición inicial, controlando la resistencia de la banda mientras lo haces.\n7 Repite el movimiento para completar el número deseado de repeticiones.'),
('Piernas', 'Sentadilla con barra', 'Agacharse y levantarse con barra detras del cuello', 'sentadilla_barra.png', '1.	Comienza de pie con los pies separados a la anchura de los hombros. Puedes colocar los pies de manera paralela o ligeramente hacia afuera, según tu comodidad.\n2.	Mantén la espalda recta, el pecho hacia afuera y los hombros hacia atrás. Mantén la mirada hacia adelante, sin mirar hacia abajo.\n3.	Extiende los brazos hacia delante para mantener el equilibrio, o puedes colocar las manos en las caderas o cruzar los brazos sobre el pecho, según tu preferencia.\n4.	Para iniciar el movimiento, flexiona las rodillas y las caderas simultáneamente, como si te estuvieras sentando en una silla. Empuja tus caderas hacia atrás mientras mantienes los talones en contacto con el suelo. Asegúrate de que las rodillas sigan la dirección de los dedos de los pies.\n5.	Continúa descendiendo hasta que los muslos estén al menos paralelos al suelo. Si tienes la flexibilidad y la fuerza necesaria, puedes bajar aún más para que tus glúteos estén cerca del suelo. Mantén el núcleo activado y los músculos abdominales apretados para mantener una buena postura.\n6.	Desde la posición más baja, comienza a ascender empujando a través de los talones y extendiendo las rodillas y las caderas. Mantén la espalda recta durante todo el movimiento.\n7.	Regresa a la posición inicial con las piernas extendidas y repite el movimiento para completar el número deseado de repeticiones.'),
('Piernas', 'Peso muerto', 'Levantar barra desde el suelo', 'peso_muerto.png', '1.	Coloca una barra en el suelo y párate frente a ella, con los pies separados a la anchura de los hombros. Puedes ajustar ligeramente la posición de los pies según tu comodidad, pero generalmente se recomienda tener los dedos de los pies apuntando ligeramente hacia afuera.\n2.	Agáchate y agarra la barra con las manos separadas a una distancia ligeramente mayor que la anchura de los hombros. Puedes usar un agarre pronunciado (palmas hacia abajo) o un agarre mixto (una palma hacia arriba y la otra hacia abajo) para asegurarte de que la barra se mantenga estable.\n3.	Mantén la espalda recta, los hombros hacia atrás y el pecho hacia adelante. Asegúrate de que tus caderas estén más altas que tus rodillas y que tu núcleo esté activado.\n4.	A medida que levantas la barra del suelo, empuja con los talones y extiende las rodillas y las caderas. Mantén la barra cerca de tu cuerpo y mantén la espalda recta durante todo el movimiento.\n5.	Continúa levantando la barra hasta que estés completamente erguido, con los hombros hacia atrás y las caderas completamente extendidas.\n6.	Para bajar la barra de manera controlada, dobla las rodillas y las caderas mientras mantienes la espalda recta. Asegúrate de mantener la barra cerca de tu cuerpo durante todo el descenso.\n7.	Coloca la barra de nuevo en el suelo con un movimiento controlado y repite el movimiento para completar el número deseado de repeticiones.\n'),
('Piernas', 'Hip trust', 'Desde el suelo y apoyado con un banco la espalda. Levantar barra desde la cadera', 'Hip_trust.png', '1.	Coloca una banca o un banco plano detrás de ti. Si es necesario, puedes colocar una almohadilla o una toalla doblada en la parte superior de la banca para mayor comodidad.\n2.	Siéntate frente a la banca y coloca la barra sobre tus caderas, justo por encima del hueso púbico. Asegúrate de que la barra esté asegurada y equilibrada.\n3.	Coloca los hombros y la parte superior de la espalda contra la banca, manteniendo los pies separados a la anchura de las caderas y las rodillas dobladas.\n4.	Asegúrate de que tus pies estén colocados de manera estable y que las rodillas estén alineadas con tus tobillos.\n5.	Contrae los glúteos y los isquiotibiales y empuja a través de los talones para elevar las caderas hacia arriba, manteniendo la espalda recta y los hombros contra la banca.\n6.	Continúa elevando las caderas hasta que tu cuerpo forme una línea recta desde las rodillas hasta los hombros. Asegúrate de apretar los glúteos en la parte superior del movimiento.\n7.	Mantén la posición de arriba durante un segundo y luego baja lentamente las caderas hacia abajo, controlando el movimiento.\n8.	Repite el movimiento para completar el número deseado de repeticiones.'),
('Piernas', 'Sentadilla libre', 'Agacharse y levantarse con el propio peso corporal', 'sentadilla_libre.png', '1.	Comienza de pie con los pies separados a la anchura de los hombros. Puedes colocar los pies de manera paralela o ligeramente hacia afuera, según tu comodidad.\n2.	Mantén la espalda recta, el pecho hacia afuera y los hombros hacia atrás. Mantén la mirada hacia adelante, sin mirar hacia abajo.\n3.	Extiende los brazos hacia delante para mantener el equilibrio, o puedes colocar las manos en las caderas o cruzar los brazos sobre el pecho, según tu preferencia.\n4.	Para iniciar el movimiento, flexiona las rodillas y las caderas simultáneamente, como si te estuvieras sentando en una silla. Empuja tus caderas hacia atrás mientras mantienes los talones en contacto con el suelo. Asegúrate de que las rodillas sigan la dirección de los dedos de los pies.\n5.	Continúa descendiendo hasta que los muslos estén al menos paralelos al suelo. Si tienes la flexibilidad y la fuerza necesaria, puedes bajar aún más para que tus glúteos estén cerca del suelo. Mantén el núcleo activado y los músculos abdominales apretados para mantener una buena postura.\n6.	Desde la posición más baja, comienza a ascender empujando a través de los talones y extendiendo las rodillas y las caderas. Mantén la espalda recta durante todo el movimiento.\n7.	Regresa a la posición inicial con las piernas extendidas y repite el movimiento para completar el número deseado de repeticiones.'),
('Piernas', 'Estocadas (Lunges)', 'Da un paso hacia adelante con una pierna y flexiona ambas rodillas para bajar el', 'Lunges.png', '1 Comienza de pie con los pies separados a la anchura de los hombros y coloca la banda elástica debajo de los pies. Asegúrate de que la banda esté tensa pero no demasiado estirada.\n2 Agarra las asas de la banda con las palmas de las manos hacia abajo y los brazos estirados a lo largo de tu cuerpo. Mantén una ligera flexión en los codos.\n3 Contrae el núcleo y mantén una postura erguida. Este será tu punto de partida.\n4 Exhala y levanta los brazos hacia adelante frente a ti, manteniendo los brazos rectos. Levanta los brazos a la altura de los hombros o ligeramente por encima de ellos. Los brazos deben estar paralelos al suelo.\n5 Mantén una breve pausa en la posición superior, sintiendo la contracción en el deltoides anterior.\n6 Inhala y lentamente baja los brazos de vuelta a la posición inicial, controlando la resistencia de la banda mientras lo haces.\n7 Repite el movimiento para completar el número deseado de repeticiones.'),
('Piernas', 'Puente Glúteo', 'Tumbado en el suelo de espalda. Levantar cadera con pies ejereciciendo fuerza ha', 'Elevacion_cadera.png', '1.	Comienza acostado boca arriba en el suelo con las rodillas dobladas y los pies apoyados en el suelo, separados a la anchura de las caderas.\n2.	Asegúrate de que tus pies estén cerca de tus glúteos, de modo que tus rodillas estén dobladas a unos 90 grados.\n3.	Coloca los brazos a lo largo del cuerpo con las palmas de las manos hacia abajo para mantener la estabilidad.\n4.	Desde esta posición, contrae los músculos del core y los glúteos, y comienza a elevar las caderas hacia el techo. Asegúrate de mantener la espalda recta durante todo el movimiento.\n5.	Continúa elevando las caderas hasta que tu cuerpo forme una línea recta desde las rodillas hasta los hombros. Aprieta los glúteos en la parte superior de la elevación.\n6.	Mantén esta posición durante un segundo y luego baja lentamente las caderas de regreso a la posición inicial.\n7.	Repite el movimiento para completar el número deseado de repeticiones.'),
('Piernas', 'Elevación de gemelos', 'Apoyado las puntas en un escalón. Dejarse caer el talón y levantarse completamen', 'Elevaciones_gemelos.png', '1 Comienza de pie con los pies separados a la anchura de los hombros y los pies apuntando hacia adelante. Puedes sostener un par de mancuernas o discos en las manos a los costados del cuerpo para agregar resistencia.\n2 Levanta los talones del suelo mientras te apoyas en las puntas de los pies. Asegúrate de mantener una buena postura con el núcleo contraído y los hombros hacia atrás.\n3 Alcanza la máxima elevación de los talones y mantén la posición durante un segundo, sintiendo la contracción en los músculos de la pantorrilla.\n4 Luego, lentamente baja los talones de vuelta al suelo, permitiendo que los músculos de la pantorrilla se estiren.\n5 Repite el movimiento para completar el número deseado de repeticiones.'),
('Espalda', 'Jalón al pecho', 'Traccionar barra de la maquina hasta el pecho', 'Jalon_pecho.png', '1. Comienza por ajustar el asiento de la máquina de polea de manera que tus pies estén apoyados de manera segura y cómoda. Asegúrate de que tus rodillas estén ligeramente flexionadas y que tus pies estén firmemente apoyados en el suelo o en los soportes de la máquina.\n2.	Agarra la barra de la polea alta con un agarre pronado (palmas hacia abajo) y las manos separadas a una anchura mayor que el ancho de los hombros. También puedes utilizar otros accesorios de agarre, como una barra en V o unas asas individuales.\n3.	Siéntate erguido en el asiento de la máquina, manteniendo la espalda recta y los hombros hacia abajo y hacia atrás. Esta es tu posición inicial.\n4.	Manteniendo los codos ligeramente flexionados, exhala y tira de la barra hacia abajo hacia tu pecho, contrayendo los músculos de la espalda baja y media. Imagina que estás llevando los codos hacia el suelo y dirigiendo los omóplatos hacia la columna vertebral.\n5.	Lleva la barra lo más cerca posible de tu pecho sin que toque tu cuerpo, manteniendo la contracción en los músculos de la espalda durante un breve instante.\n6.	Inhala y de manera controlada, regresa la barra a la posición inicial, extendiendo los brazos y estirando los músculos de la espalda.\n7.	Repite el movimiento durante el número deseado de repeticiones, manteniendo la técnica adecuada y controlando el movimiento en todo momento.'),
('Espalda', 'Remo mancuerna', 'Inclinado 45º apoyado en banco traccionar mancuerna unilateralmente', 'Remo_macuerna', '1 Comienza de pie con los pies separados a la anchura de los hombros. Toma una mancuerna con una mano y deja que el brazo cuelgue recto hacia abajo.\n2  Dóblate hacia adelante desde la cintura, manteniendo la espalda recta y el núcleo contraído. Inclínate lo suficiente para que el torso esté casi paralelo al suelo, manteniendo una ligera flexión en las rodillas.\n3 Con el brazo extendido, inhala y tira de la mancuerna hacia arriba, llevando el codo hacia atrás y manteniendo el brazo cerca del torso. El movimiento debe ser similar a tirar de un remo. Mantén el hombro hacia abajo y hacia atrás para activar los músculos de la espalda.\n4 Lleva la mancuerna hacia arriba hasta que el codo esté en línea con el torso o ligeramente por encima de él. Mantén la contracción en la espalda alta durante un segundo.\n5 Luego, exhala y baja lentamente la mancuerna hacia abajo, estirando el brazo completamente hacia abajo.\n6 Repite el movimiento para completar el número deseado de repeticiones y luego cambia de mano para trabajar el otro lado de manera equilibrada.'),
('Espalda', 'Dominadas', 'Agarra una barra encima tuya y traccionar hasta tocar el pecho la barra', 'dominada.png', '1.	Busca una barra de dominadas estable y colócate debajo de ella. Puedes utilizar una barra de dominadas en un parque, un gimnasio o instalar una barra de dominadas en tu casa si es posible.\n2.	Agarra la barra con las palmas hacia adelante (agarre pronado) y las manos un poco más separadas que el ancho de los hombros. También puedes utilizar un agarre con las palmas hacia adentro (agarre supino) o un agarre mixto (una mano con las palmas hacia adelante y la otra con las palmas hacia adentro), dependiendo de tus preferencias y nivel de fuerza.\n3.	Desde una posición colgante con los brazos completamente extendidos, inhala y contrae los músculos abdominales.\n4.	Comienza a elevar tu cuerpo hacia la barra, doblando los codos y tirando de los hombros hacia abajo y hacia atrás. Intenta llevar tu pecho hacia la barra.\n5.	Continúa subiendo hasta que tu barbilla esté por encima de la barra y tus hombros estén cerca de las orejas. Mantén una buena postura corporal, evitando balancear el cuerpo o usar impulso.\n6.	Pausa brevemente en la posición más alta y luego exhala mientras desciendes lentamente, volviendo a la posición colgante con los brazos extendidos.\n7.	Repite el movimiento durante el número deseado de repeticiones, manteniendo la técnica adecuada y controlando el movimiento en todo momento.'),
('Espalda', 'Remos Invertidos', 'Consiste en agarrarse a una barra horizontal con las manos separadas al ancho de', 'Remo_invertido.png', '1.	Busca una barra horizontal o una barra de dominadas baja que esté a una altura adecuada para que puedas agarrarla estando acostado debajo de ella. También puedes utilizar un bastidor de sentadillas ajustando los soportes a una altura adecuada.\n2.	Acuéstate boca arriba debajo de la barra, con las piernas extendidas y los talones apoyados en el suelo. Asegúrate de que tu cuerpo esté recto y alineado.\n3.	Agarra la barra con las palmas de las manos hacia abajo (agarre pronado) y las manos un poco más anchas que el ancho de los hombros. También puedes usar un agarre supino (palmas hacia arriba) o un agarre mixto, según tus preferencias y nivel de fuerza.\n4.	Desde esta posición inicial, inhala y comienza a tirar de tu cuerpo hacia arriba, doblando los codos y llevando el pecho hacia la barra. Mantén los hombros hacia abajo y hacia atrás para enfocar el trabajo en los músculos de la espalda.\n5.	Continúa levantando tu cuerpo hasta que el pecho toque la barra o hasta que los brazos estén completamente flexionados. Mantén una buena postura y evita balancear el cuerpo o arquear la espalda.\n6.	Pausa brevemente en la posición más alta y luego exhala mientras desciendes lentamente, extendiendo los brazos y volviendo a la posición inicial.\n7.	Repite el movimiento durante el número deseado de repeticiones, manteniendo la técnica adecuada y controlando el movimiento en todo momento.'),
('Brazos', 'Remo supinos o Australianas', 'Consiste en agarrarse a una barra horizontal con las manos separadas y palmas mi', 'Remo_supino.png', '1 Busca una barra de dominadas horizontal o una barra Smith a una altura adecuada para que puedas colgarte debajo de ella. La barra debe estar lo suficientemente alta para que puedas extender los brazos completamente cuando estás acostado en el suelo.\n2 Acuéstate en el suelo debajo de la barra y extiende los brazos para agarrarla con un agarre supino, es decir, las palmas de las manos hacia arriba y las manos separadas a una anchura un poco mayor que la anchura de los hombros.\n3 Mantén los pies apoyados en el suelo y levanta el cuerpo hasta que estés completamente extendido, manteniendo una línea recta desde los hombros hasta los pies. Esta será tu posición inicial.\n4 A medida que inhalas, dobla los codos y tira del pecho hacia la barra, manteniendo los codos cerca del cuerpo. Mantén los hombros hacia atrás y hacia abajo, y enfócate en activar los músculos de la espalda durante todo el movimiento.\n5 Lleva el pecho lo más cerca posible de la barra y mantén la posición durante un segundo, sintiendo la contracción en los músculos de la espalda.\n6 Exhala mientras extiendes los brazos nuevamente y bajas el cuerpo de manera controlada hasta la posición inicial.\n7 Repite el movimiento para completar el número deseado de repeticiones.'),
('Brazos', 'Fondos en Banco', 'Manos apoyadas detrás nuestra en un punto de apoyo dejarse caer y luego ejercer ', 'Fondo_banco.png', '1 Encuentra un banco o una plataforma elevada resistente. Debe ser lo suficientemente estable para soportar tu peso corporal.\n2 Colócate de espaldas al banco y siéntate en el borde del mismo. Coloca las manos a cada lado de las caderas, agarrando el borde del banco con los dedos mirando hacia adelante.\n3 Camina hacia adelante, deslizando los glúteos fuera del banco. Mantén los talones apoyados en el suelo y las piernas estiradas frente a ti. Los brazos deben estar completamente extendidos.\n4 A medida que inhalas, dobla los codos y comienza a descender el cuerpo hacia el suelo. Mantén el torso erguido y los codos cerca del cuerpo durante todo el movimiento.\n5 Continúa bajando hasta que los hombros estén a la altura de los codos o ligeramente por debajo de ellos. Mantén la posición durante un segundo, sintiendo la contracción en los músculos del tríceps.\n6 A medida que exhalas, empuja hacia arriba con los brazos y vuelve a la posición inicial, extendiendo completamente los codos.\n7 Repite el movimiento para completar el número deseado de repeticiones'),
('Brazos', 'Curl biceps martillo', 'Levantar mancuerna vertical unilateral', 'Curl_martillo.png', '1. Toma una mancuerna en cada mano y mantén los brazos a los lados con las palmas de las manos mirando hacia tu cuerpo. Esta posición se llama agarre neutro o agarre martillo.\n2.	Mantén los pies separados a la anchura de los hombros y mantén una postura erguida y estable.\n3.	Comienza el movimiento doblando los codos y levantando las mancuernas hacia los hombros. Asegúrate de mantener los codos cerca del cuerpo y los antebrazos paralelos al suelo.\n4.	Continúa elevando las mancuernas hasta que los antebrazos estén en posición vertical y las mancuernas estén cerca de los hombros.\n5.	Mantén la contracción en los músculos del brazo durante un segundo en la parte superior del movimiento.\n6.	Luego, baja lentamente las mancuernas de regreso a la posición inicial, manteniendo el control del movimiento.\n7.	Repite el movimiento para completar el número deseado de repeticiones'),
('Brazos', 'Extensión triceps cuerda', 'Coger cuerda detrás de la cabeza y cuerpo inclinado en 45º', 'Extensión_cuerda_triceps.webp', '1 Comienza de pie frente a una máquina de poleas o con la banda elástica asegurada a una posición estable y a una altura adecuada. Agarra el extremo de la cuerda o las asas de la banda elástica con ambas manos.\n2 Da un paso hacia atrás para crear tensión en la cuerda o en la banda elástica. Mantén los pies separados a la anchura de los hombros y flexiona ligeramente las rodillas.\n3 Mantén una postura erguida con el torso recto y los hombros hacia atrás. Este será tu punto de partida.\n4 Manteniendo los codos cerca del cuerpo, exhala y comienza a extender los antebrazos hacia abajo, alejando las manos de la cabeza. El movimiento debe ser una extensión completa de los brazos.\n5 Mantén una breve pausa en la posición final, sintiendo la contracción en los músculos tríceps.\n6 Inhala y, de manera controlada, vuelve a la posición inicial flexionando los codos y llevando las manos hacia la cabeza.\n7 Repite el movimiento para completar el número deseado de repeticiones.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `listamateriales`
--

CREATE TABLE `listamateriales` (
  `titulo` varchar(80) DEFAULT NULL,
  `nombre` varchar(80) DEFAULT NULL,
  `descripcion` varchar(80) DEFAULT NULL,
  `imagen` varchar(50) DEFAULT NULL,
  `explicacion` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `listamateriales`
--

INSERT INTO `listamateriales` (`titulo`, `nombre`, `descripcion`, `imagen`, `explicacion`) VALUES
('Material', 'Mancuerna', 'Barra corta y pesada con un agarre en el centro', 'Mancuerna.png', 'Barra: La barra de la mancuerna es una vara corta y recta que generalmente tiene una longitud de aproximadamente 30 a 45 centímetros. Puede estar hecha de diferentes materiales como acero, hierro, plástico o incluso caucho. La barra puede ser lisa o tener un agarre texturizado para mejorar el agarre durante el ejercicio.\nPeso: Cada extremo de la barra tiene un peso fijo o ajustable, lo que permite variar la carga de acuerdo a las necesidades individuales. Los pesos de las mancuernas pueden variar desde unos pocos kilogramos hasta más de 50 kilogramos, dependiendo del tipo y modelo.\nAgarre: El agarre de la mancuerna puede ser recto o ergonómico, dependiendo del diseño. El agarre ergonómico tiene una forma contorneada que se adapta mejor a la mano, lo que proporciona una mayor comodidad y estabilidad durante el levantamiento.\nSeguridad: Algunas mancuernas cuentan con mecanismos de seguridad, como cierres o seguros, que aseguran que los pesos estén bien sujetos a la barra y evitan que se deslicen o se desprendan durante el ejercicio.\nVariabilidad: Una de las ventajas de las mancuernas es su versatilidad y capacidad para realizar una amplia variedad de ejercicios. Puedes realizar levantamientos individuales o bilaterales, trabajar diferentes grupos musculares y adaptar la carga según tus objetivos y nivel de fuerza.'),
('Material', 'Barra olímpica', 'Barra larga y pesada', 'Barra_olimpica.png', 'Longitud: Una barra olímpica tiene una longitud estándar de 220 centímetros (7.2 pies). Esta longitud permite un agarre amplio para los levantamientos de arrancada y envión en la halterofilia, así como una posición cómoda para ejercicios como sentadillas y press de banca.\nPeso: Una barra olímpica tiene un peso estándar de 20 kilogramos (44 libras) para las barras utilizadas en las competiciones femeninas, y 20 kilogramos a 20.4 kilogramos (44 a 45 libras) para las barras utilizadas en las competiciones masculinas. También existen barras olímpicas de menor peso, como las de 15 kilogramos (33 libras), diseñadas para principiantes y personas con menos fuerza.\nDiámetro: El diámetro de una barra olímpica suele ser de 28 a 29 milímetros en la zona de agarre. Esto proporciona un buen agarre para los levantadores y les permite mantener el control de la barra durante los movimientos rápidos y explosivos.\nAgarre: La barra olímpica tiene una textura rugosa en la zona de agarre para proporcionar mayor adherencia. Esta textura puede variar según la marca y el modelo de la barra, pero suele ser suficiente para permitir un agarre seguro incluso cuando se suda durante los levantamientos.\nMarcas de agarre: En una barra olímpica, hay marcas en el centro de la barra y a lo largo de los extremos que indican la posición de agarre estándar para los diferentes levantamientos, como la arrancada, el envión y el levantamiento de potencia.\nCapacidad de carga: Una barra olímpica está diseñada para soportar cargas pesadas. La capacidad de carga puede variar según el tipo de barra, pero la mayoría de las barras olímpicas pueden soportar entre 450 y 900 kilogramos (1000 a 2000 libras) de peso total.'),
('Material', 'Agarre cuerda', ',Cuerda en forma de v con enganche en maquina con poleas', 'Agarre_cuerda.png', 'Nylon: El nylon es un material sintético resistente y duradero que se utiliza comúnmente en cuerdas y mangos de agarre. Es conocido por su resistencia al desgaste, la abrasión y la tracción, lo que lo hace ideal para soportar la tensión generada durante los ejercicios de entrenamiento de fuerza.\nPoliéster: El poliéster es otro material sintético que se utiliza en cuerdas y agarres de cuerda. Es resistente, duradero y tiene propiedades similares al nylon en términos de resistencia al desgaste y a la tracción.\nCaucho: Algunas cuerdas pueden estar recubiertas con una capa de caucho para mejorar el agarre y la comodidad durante el ejercicio. El caucho proporciona una superficie antideslizante y resistente al desgaste, lo que ayuda a mantener un agarre firme durante los movimientos.\nEspuma: En algunos casos, los mangos de agarre de cuerda pueden estar recubiertos con una capa de espuma para proporcionar una superficie más cómoda y acolchada para las manos. Esto puede ser especialmente beneficioso para reducir la incomodidad o el dolor en las palmas durante ejercicios de alto impacto.'),
('Material', 'Maquina Polea', 'Consiste en una estructura metálica con un sistema de poleas con o sin asientos', 'Maquina_polea.jpg', 'Estructura: Una máquina de polea consta de una estructura resistente que soporta las poleas y los cables. Puede tener un diseño independiente o estar integrada en una estación de entrenamiento multifuncional.\nPoleas: Las poleas son ruedas con ranuras que permiten que los cables se muevan de manera fluida. En las máquinas de polea, se utilizan poleas fijas o poleas ajustables para variar la dirección y la tensión del cable.\nCables: Los cables son cuerdas de acero o de materiales resistentes que están conectados a las poleas y proporcionan la resistencia necesaria durante el ejercicio. Los cables se ajustan en longitud para adaptarse a diferentes ejercicios y rangos de movimiento.\nPlacas de peso o sistema de carga: Para ajustar la resistencia, las máquinas de polea pueden utilizar placas de peso que se añaden o se retiran para modificar la carga. También existen máquinas de polea que utilizan sistemas de carga basados en pistones o bandas elásticas.\nAgarres y accesorios: Las máquinas de polea suelen estar equipadas con una variedad de agarres y accesorios intercambiables que permiten realizar diferentes ejercicios y trabajar diferentes grupos musculares. Estos pueden incluir barras rectas, barras en forma de cuerda, asas de agarre neutro, asas de agarre supino y más.\nAjustes y posiciones: La mayoría de las máquinas de polea permiten ajustar la altura y la posición del asiento o del soporte para adaptarse a diferentes tamaños de cuerpo y rangos de movimiento. Esto facilita la realización de ejercicios en diferentes planos y ángulos.'),
('Material', 'Banda elástica', 'Material de goma con elasticidad y resistencia', 'Banda_elastica.png', 'Tipos y resistencia: Las bandas elásticas vienen en diferentes tipos y niveles de resistencia, que se clasifican por colores o niveles. Las bandas más delgadas y más ligeras ofrecen menos resistencia, mientras que las bandas más anchas y más pesadas proporcionan una mayor resistencia. Puedes elegir la banda elástica que se adapte a tu nivel de fuerza y al ejercicio específico que deseas realizar.\nEjercicios: Las bandas elásticas se pueden utilizar para una amplia variedad de ejercicios de entrenamiento de fuerza, estiramiento y rehabilitación. Puedes realizar ejercicios para trabajar diferentes grupos musculares, como brazos, hombros, espalda, pecho, glúteos y piernas. Algunos ejercicios comunes con bandas elásticas incluyen extensiones de tríceps, filas, prensas de pecho, sentadillas y estocadas.\nPortabilidad y versatilidad: Una de las ventajas de las bandas elásticas es que son portátiles y pueden llevarse a cualquier lugar. Son un equipo ligero y compacto que se puede guardar fácilmente en una mochila o maleta, lo que las hace ideales para el entrenamiento en casa, en el gimnasio o incluso cuando se está de viaje.\nNiveles de resistencia ajustables: Si tienes bandas elásticas con diferentes niveles de resistencia, puedes ajustar la intensidad del ejercicio cambiando la banda. Puedes progresar gradualmente aumentando la resistencia a medida que tu fuerza y resistencia mejoran.\nSeguridad y precauciones: Asegúrate de usar la banda elástica de manera segura. Antes de cada uso, verifica que la banda esté en buenas condiciones sin signos de desgaste o roturas. Además, evita estirar demasiado la banda y suéltala suavemente después de cada repetición para evitar el riesgo de lesiones si se suelta bruscamente.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE `usuario` (
  `nombre` varchar(80) DEFAULT NULL,
  `email` varchar(80) NOT NULL,
  `contraseña` varchar(80) DEFAULT NULL,
  `fechaNacimiento` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `usuario`
--

INSERT INTO `usuario` (`nombre`, `email`, `contraseña`, `fechaNacimiento`) VALUES
('a', 'a', 'a', '2023-05-19'),
('aaa', 'aaa', 'aaa', '2023-07-18'),
('as', 'as', 'as', '2023-05-10'),
('243', 'asdf', 'asdf', '2023-05-10'),
('b', 'b', 'b', '1989-09-14'),
('bb', 'bb', 'bb', '2023-05-09'),
('bbb', 'bbb', 'bbb', '2023-05-10'),
('bbbb', 'bbbb', 'bbbb', '2023-05-11'),
('c', 'c', 'c', '2023-05-18'),
('carloos', 'carlos', 'carlos', '2023-05-09'),
('chicu', 'chicu', 'chicu', '2023-05-09'),
('dd', 'dd', 'dd', '2023-05-25'),
('d', 'e', 'd', '2023-05-17'),
('f', 'f', 'f', '2023-05-10'),
('jose', 'josse', 'jose', '1999-09-17'),
('ju', 'ju', 'ju', '2023-05-01'),
('polo', 'polo', 'polo', '2023-05-13'),
('v', 'v', 'v', '2023-06-22');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `entrenamiento`
--
ALTER TABLE `entrenamiento`
  ADD KEY `fk_email_usuario` (`email_usuario`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`email`);

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `entrenamiento`
--
ALTER TABLE `entrenamiento`
  ADD CONSTRAINT `fk_email_usuario` FOREIGN KEY (`email_usuario`) REFERENCES `usuario` (`email`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
